# Generated by Django 4.1.1 on 2022-09-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0013_address_cep"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnuncioVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_prod", models.CharField(max_length=100)),
                ("descricao_prod", models.TextField()),
                ("quantidade_prod", models.IntegerField()),
                (
                    "img_prod",
                    models.ImageField(blank=True, null=True, upload_to="marketplace"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("A", "Ativo"), ("I", "Inativo")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("preco_prod", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "address_prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnuncioDoacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_prod", models.CharField(max_length=100)),
                ("descricao_prod", models.TextField()),
                ("quantidade_prod", models.IntegerField()),
                (
                    "img_prod",
                    models.ImageField(blank=True, null=True, upload_to="marketplace"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("A", "Ativo"), ("I", "Inativo")],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "address_prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
