# Generated by Django 4.1.1 on 2022-09-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_anunciodoacao_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="anunciodoacao",
            old_name="address_prod",
            new_name="endereco_prod",
        ),
        migrations.RenameField(
            model_name="anunciodoacao",
            old_name="state",
            new_name="estado",
        ),
        migrations.RenameField(
            model_name="anunciovenda",
            old_name="address_prod",
            new_name="endereco_prod",
        ),
        migrations.RenameField(
            model_name="anunciovenda",
            old_name="state",
            new_name="estado",
        ),
    ]
