# Generated by Django 4.1.1 on 2022-09-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketplace",
            "0003_rename_address_prod_anunciodoacao_endereco_prod_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="anunciodoacao",
            name="categoria",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Categoria do Produto"
            ),
        ),
        migrations.AddField(
            model_name="anunciovenda",
            name="categoria",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Categoria do Produto"
            ),
        ),
    ]
