# Generated by Django 4.1.1 on 2022-09-09 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketplace", "0005_anunciodoacao_user_anunciovenda_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anunciodoacao",
            name="categoria",
            field=models.CharField(max_length=100, verbose_name="Categoria do Produto"),
        ),
        migrations.AlterField(
            model_name="anunciodoacao",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="anunciovenda",
            name="categoria",
            field=models.CharField(max_length=100, verbose_name="Categoria do Produto"),
        ),
        migrations.AlterField(
            model_name="anunciovenda",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
