# Generated by Django 4.1.1 on 2022-09-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_alter_anunciodoacao_categoria_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anunciodoacao",
            name="endereco_prod",
        ),
        migrations.RemoveField(
            model_name="anunciovenda",
            name="endereco_prod",
        ),
        migrations.AddField(
            model_name="anunciodoacao",
            name="cidade",
            field=models.CharField(
                default="", max_length=100, verbose_name="Cidade do Produto"
            ),
        ),
        migrations.AddField(
            model_name="anunciovenda",
            name="cidade",
            field=models.CharField(
                default="", max_length=100, verbose_name="Cidade do Produto"
            ),
        ),
        migrations.AlterField(
            model_name="anunciodoacao",
            name="categoria",
            field=models.CharField(
                default="Outros", max_length=100, verbose_name="Categoria do Produto"
            ),
        ),
        migrations.AlterField(
            model_name="anunciodoacao",
            name="quantidade_prod",
            field=models.IntegerField(default=1, verbose_name="Quantidade do Produto"),
        ),
        migrations.AlterField(
            model_name="anunciovenda",
            name="categoria",
            field=models.CharField(
                default="Outros", max_length=100, verbose_name="Categoria do Produto"
            ),
        ),
        migrations.AlterField(
            model_name="anunciovenda",
            name="quantidade_prod",
            field=models.IntegerField(default=1, verbose_name="Quantidade do Produto"),
        ),
    ]
