# Generated by Django 4.1.1 on 2022-09-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="lastname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
