# Generated by Django 4.1.1 on 2022-09-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
