# Generated by Django 4.1.1 on 2022-09-13 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='', max_length=100, null=True)),
                ('number', models.IntegerField(default=0)),
                ('district', models.CharField(default='', max_length=100, null=True)),
                ('complement', models.CharField(default='', max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='', max_length=2)),
                ('cep', models.CharField(default='', max_length=8, null=True)),
            ],
            options={
                'verbose_name_plural': "Address's",
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cnpj', models.CharField(max_length=14, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('logo', models.ImageField(blank=True, upload_to=utils.upload_logo_formatter)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.address')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Company's",
            },
        ),
    ]
