# Generated by Django 4.0.6 on 2022-08-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_address_id_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id_company',
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.address'),
        ),
    ]
