# Generated by Django 4.0.6 on 2022-08-01 15:17

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_address_id_company_alter_company_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': "Address's"},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': "Company's"},
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to=company.models.upload_logo_formatter),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
