# Generated by Django 4.0.6 on 2022-08-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_address_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone (ddd + number)',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
