# Generated by Django 4.0.6 on 2022-08-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_phone (ddd + number)_company_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.AddField(
            model_name='company',
            name='phone (ddd + number)',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
