# Generated by Django 4.0.6 on 2022-08-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_company_phone_company_phone (ddd + number)'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='phone (ddd + number)',
            new_name='phone',
        ),
    ]
