# Generated by Django 4.1.1 on 2022-09-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_alter_company_cnpj"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="district",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
