# Generated by Django 4.1.1 on 2022-09-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0012_address_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="cep",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
