name: ci

on:
    push:
        branches:
        - '*'
        - main
        - master
        - develop
    
    workflow_dispatch:

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Docker login
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Docker build and push
          if: github.ref != 'refs/heads/master' ||
              github.ref != 'refs/heads/develop' ||
              github.ref != 'refs/heads/release/*' ||
              github.ref == 'refs/haeds/*'

          uses: docker/build-push-action@v3.0.0
          with:
            file: ./Dockerfile
            context: .
            push: true
            tags: |
                ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
                ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.run_number }}

            run: |
                echo "${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.run_number }}"